dist: focal
language: python
python:
- '3.8'
- '3.9'
- '3.10'
services:
- mysql
install:
- python3 -m pip install -r requirements.txt
before_script:
- mysql -e 'CREATE DATABASE cardinal;'
- mysql -u root --password="" cardinal < sql/cardinal.sql
- mysql -e 'SHOW TABLES from cardinal;'
- ls -lah
script:
- bash ci/tests/travis-test.sh
