# Cardinal (Default Configuration for Kubernetes)

apiVersion: v1
data:
  .dockerconfigjson: <DOCKER_CONFIG_SECRET_TOKEN>
kind: Secret
metadata:
  creationTimestamp: null
  name: <CONTAINER_REGISTRY_PULL_SECRET_NAME> # for example, 99-99-99-99-nip-io-imagepullsecret
type: kubernetes.io/dockerconfigjson